name: Build and Release

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'jetbrains'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: chmod u+x ./gradlew && ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: build/libs/
          name: artifact

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: artifact

      - name: Set release file path
        id: set_release_file
        run: |
          if [ -f *-all.jar ]; then
            echo "path=*-all.jar" >> $GITHUB_OUTPUT
          else
            echo "path=*.jar" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ${{ steps.set_release_file.outputs.path }}
